name: chameleon manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'chameleon/**', '.github/**' ]
    tags:
      - "v*.*.*"

jobs:
  Build_Chameleon:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc weasyprint texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          sudo pip install pandoc-secnos

      - name: Build Fancy Version
        run: |
          cd ${{github.workspace}}/chameleon/manual
          latex --version
          pandoc *.md -o chameleon_manual.pdf --filter pandoc-secnos --pdf-engine=weasyprint --css ${{github.workspace}}/common/style_dark.css

      - name: Build Print Version
        run: |
          cd ${{github.workspace}}/chameleon/manual
          pandoc *.md -o chameleon_manual_print.pdf --filter pandoc-secnos --pdf-engine=weasyprint --css ${{github.workspace}}/common/style_print.css

      - uses: actions/upload-artifact@v4
        with:
          name: chameleon_manual
          path: |
            ${{github.workspace}}/chameleon/manual/chameleon_manual.pdf
            ${{github.workspace}}/chameleon/manual/chameleon_manual_print.pdf
          overwrite: 'true'
