name: chameleon manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'chameleon/**', '.github/**', 'common/**' ]

jobs:
  Build_Chameleon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc weasyprint texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra fonts-roboto
          sudo pip install pandoc-secnos

      - name: Setup Environment Variables
        shell: bash
        run: |
          echo "BUILD_FOLDER=${{github.workspace}}/build/chameleon" >> $GITHUB_ENV

      - name: run build script
        run: scripts/build_chameleon.sh

      - uses: actions/upload-artifact@v4
        with:
          name: chameleon_manual
          path: |
            ${{ env.BUILD_FOLDER }}/chameleon_manual.pdf
            ${{ env.BUILD_FOLDER }}/chameleon_manual_print.pdf
          overwrite: 'true'
