name: chameleon manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'chameleon/**', '.github/**' ]
    tags:
      - "v*.*.*"

jobs:
  Build_Chameleon:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc weasyprint texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra fonts-roboto tree
          sudo pip install pandoc-secnos
      
      - name: Setup Environment Variables
        shell: bash
        run: |
          echo "BUILD_FOLDER=${{github.workspace}}/build" >> $GITHUB_ENV
        
      - name: Copy to tmp folder
        run: |
          cd ${{github.workspace}}/chameleon/manual
          mkdir ${{ env.BUILD_FOLDER }}/
          cp -r assets ${{ env.BUILD_FOLDER }}/
          cp *.md ${{ env.BUILD_FOLDER }}/
          cp ${{github.workspace}}/common/controls/*.md ${{ env.BUILD_FOLDER }}/
          cp ${{github.workspace}}/common/style_dark.css ${{ env.BUILD_FOLDER }}/
          cp ${{github.workspace}}/common/style_print.css ${{ env.BUILD_FOLDER }}/
          tree ${{ env.BUILD_FOLDER }}/

      # setting the metadata title changes the title displayed by pdf-viewers, but introduces a separate heading (which is undesired). To remove that, set the title variable to null
      - name: Build Fancy Version
        run: |
          cd ${{ env.BUILD_FOLDER }}/
          pandoc *.md -o chameleon_manual.pdf --filter pandoc-secnos --pdf-engine=weasyprint --css style_dark.css --metadata title="Chameleon" -V "title:"

      # setting the metadata title changes the title displayed by pdf-viewers, but introduces a separate heading (which is undesired). To remove that, set the title variable to null
      - name: Build Print Version
        run: |
          cd ${{ env.BUILD_FOLDER }}/
          pandoc *.md -o chameleon_manual_print.pdf --filter pandoc-secnos --pdf-engine=weasyprint --css style_print.css --metadata title="Chameleon" -V "title:"

      - uses: actions/upload-artifact@v4
        with:
          name: chameleon_manual
          path: |
            ${{ env.BUILD_FOLDER }}/chameleon_manual.pdf
            ${{ env.BUILD_FOLDER }}/chameleon_manual_print.pdf
          overwrite: 'true'
