name: sloth manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Build_Sloth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          pip install pandoc-secnos

      - name: Build
        run: |
          cd ${{github.workspace}}/sloth/manual
          pandoc *.md -o sloth_manual.pdf -V colorlinks=true -V linkcolor=blue -V urlcolor=blue --number-sections --filter pandoc-secnos
          
