name: sloth manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Build_Sloth:
    runs-on: ubuntu-latest
    steps:
      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@v1
        with:
          args: '${{github.workspace}}/sloth/manual/*.md -s -o sloth_manual.pdf -V colorlinks=true -V linkcolor=blue -V urlcolor=blue --number-sections --filter pandoc-secnos'

