name: sloth manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Build_Sloth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install pandoc-secnos --user

      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@v1
        with:
          args: 'sloth/manual/01_header.md -s -o sloth_manual.pdf -V colorlinks=true -V linkcolor=blue -V urlcolor=blue --number-sections --filter pandoc-secnos'

