name: sloth manual

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'sloth/**', '.github/**' ]

jobs:
  Build_Sloth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc weasyprint texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra fonts-roboto
          sudo pip install pandoc-secnos

      # setting the metadata title changes the title displayed by pdf-viewers, but introduces a separate heading (which is undesired). To remove that, set the title variable to null
      - name: Build Fancy Version
        run: |
          cd ${{github.workspace}}/sloth/manual
          pandoc *.md -o sloth_manual.pdf --filter pandoc-secnos --pdf-engine=weasyprint --css ${{github.workspace}}/common/style_dark.css --metadata title="Sloth" -V "title:"

      - uses: actions/upload-artifact@v4
        with:
          name: sloth_manual
          path: ${{github.workspace}}/sloth/manual/sloth_manual.pdf
          overwrite: 'true'
